# Theme Configuration

# site
title: UMATOBU'S BLOG
subtitle: sharing, open source, interesting
description: record the history of the academic qualifications, the interesting things and the sentiments of life
keywords: c++,Qt,opengl,opencv
author: umatobu

# URL
url:
  blog_url: https://github.com/umatobu
  theme_url: https://github.com/umatobu/hexo-theme-umatobu

# contact
contact:
  email: umatobu@163.com

# menu
menu:
  HOME: /
  ARCHIVES: /archives
  ABOUTME: /aboutme

# icon
icon:
  head: /icon/favicon.png
  header_logo: /icon/header_logo.png