# Theme Configuration

# site
title: UMATOBU'S BLOG
subtitle: sharing, open source, interesting
description: record the history of the academic qualifications, the interesting things and the sentiments of life
keywords: c++,Qt,opengl,opencv
author: umatobu

# URL
url:
  blog_url: https://github.com/umatobu
  theme_url: https://github.com/umatobu/hexo-theme-umatobu

# menu
menu:
  HOME: /
  ARCHIVES: /archives
  ABOUTME: /aboutme

# icon
icon:
  head: /icon/favicon.png
  header_logo: /icon/header_logo.png

# me
me:
  photo: /photo/head.png
  name: umatobu
  telephone: +86-1873713xxxx
  email: umatobu@163.com
  address: GuangWu Road, Xingyang County, Zhengzhou City
  university: Zhengzhou University of Light Industry
  major: computer science and Technology
  github: https://github.com/umatobu